# Generated by Django 4.2.3 on 2023-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('keyword', 'Keyword'), ('source', 'Source')], default='source', max_length=20),
        ),
    ]
