# Generated by Django 4.2.3 on 2023-08-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0003_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
        ),
    ]
