# Generated by Django 4.2.3 on 2023-08-10 17:30

import cleaner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0006_filedownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(max_length=500, upload_to=cleaner.models.get_upload_to),
        ),
    ]
